### ISSUE TITLE
Redundant application entries

### ISSUE THREAD

**Issue by dkadioglu** [openSUSE/kmozillahelper#1]
Hi,

when I browse to some file, e.g. a PDF file, and I want to use a specific application, I click on "Other..." (I'm using the german version, so I am not sure if that is the correct english string) and can then choose from all applications installed on my system. As you can see on the screenshots, some application entries appear multiple times.
![firefox_kde1](https://cloud.githubusercontent.com/assets/1633773/11943527/d65284b6-a83e-11e5-97ca-162b0af56116.png)
![firefox_kde2](https://cloud.githubusercontent.com/assets/1633773/11943528/d96e790c-a83e-11e5-83bb-373b0aed3677.png)
![firefox_kde3](https://cloud.githubusercontent.com/assets/1633773/11943529/db45c5be-a83e-11e5-9d9b-3affe32af4a5.png)

Can this be changed? Would it be possible, to visualize the installed applications according to their categories like it was the case in KDE 4, which means all applications for images/pictures under Graphics and all applications like Libreoffice under Office, etc.?

Another really small problem is the string "label" which you can see on the second and third screenshot. Am I right that there should actually be another heading?

If you need further information, please ask.

Thanks in advance!

**Comment by dkadioglu** [comment]
It seems that the dialog on the screenshots is actually not the KDE/Plasma one but, instead from something else - Firefox? GTK2? GTK3? I can't tell...
Does the "Open with" dialog from KDE/Plasma work with the kf5 ported kmozillahelper? Could somebody else check that? If so, could I maybe miss some dependency during compilation?

**Comment by dkadioglu** [comment]
Hi again,
as this still occurs with recent Firefox 45 and I got no response I would like to ask again, if others see the KDE/Plasma dialog!?

Thanks!

**Comment by Vogtinator** [comment]
I see the KDE/Plasma dialog here when downloading from the PDF viewer. So something is not right with your setup:

![image](https://cloud.githubusercontent.com/assets/1622084/21956439/0afc53b6-da81-11e6-9b8f-ad1d3882f971.png)

**Comment by Vogtinator** [comment]
Closed due to WORKSFORME NORESPONSE.

**Comment by Brli** [comment]
This is an GTK3 build of firefox.

firefox doesn't prompt KDE application chooser as expected, rather, it fallback to the GTK3 file chooser as shown at first post

**Comment by Vogtinator** [comment]
Can confirm, it's broken with a GTK 3 build

**Comment by wrosenauer** [comment]
I can easily imagine that the Gtk3 codepath is not patched in Firefox correctly yet. I will check.

**Comment by wrosenauer** [comment]
With Gtk3 Mozilla introduced an extra application chooser.
So I meanwhile found what is happening and I have a bandaid patch ready to test soon. Just from the implementation it's not exactly complete and nice but I'd like to ship this with FF52 coming week if possible. It still might be too late if it doesn't work out but will keep looking into it for a proper patch still.

**Comment by wrosenauer** [comment]
http://www.rosenauer.org/hg/mozilla/file/ce8a98f8d8d7/mozilla-kde.patch contains the bandaid and I will add it to the Firefox 52.0 package.
There is a limitation with the current patch:
If KDE is running under a Gtk3 enabled Firefox without kmozillahelper the Gtk3 application chooser will never appear and it will (hopefully) fall back to the Gtk2 behaviour.

In any case it seems the Gtk3 application chooser as can be seen above has a few issues like duplicate entries and also the "label" string which is strange. But also not in scope of this project and issue tracker.
I think this can be closed.

**Comment by Brli** [comment]
it kinda works with kmozillahelper for now, maybe not perfect yet. thanks @wrosenauer for shipping the patch in time.
