### ISSUE TITLE
"Save" isn't reliable ...

### ISSUE THREAD

**Issue by Brli** [openSUSE/kmozillahelper#12]
... When:

- Right click on links > Save Link as
- Redirect by online storage services ie. Mega, Google Drive etc.
- All the others

Reproduce steps:

- right click on my avatar
- "save image as"
- greet with kde prompt
- change to a place of your choic, click "Save" (happens even directly press Save)
- Nothing happens
  - the download toolbar icon (down arrow) doesn't blink
  - check the download manager, nothing is done
  - check the destination directory, no such file

- retry a few times, and it suddenly works

Expected behaviour:

- should always be reliable at first time being prompt and confirm saved place.

**Comment by Vogtinator** [comment]
Any messages in the firefox terminal output messages?

**Comment by Brli** [comment]
```
kf5.kio.core: Invalid URL: QUrl("1622084.png")
kf5.kio.core: KSambaShare: Could not find smb.conf!
kf5.kio.core: Invalid URL: QUrl("1622084.png")
```

**Comment by Vogtinator** [comment]
Those are kio-internal warnings caused by specifiying the prefilled file name in the dialog and can be ignored. I cannot reproduce the issue here, which version of firefox and kmozillahelper do you use?

**Comment by Brli** [comment]
kmozillahelper 21af64b
firefox 51.0.1 with [kde patch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-kde-opensuse) but without unity-menubar.patch

**Comment by Vogtinator** [comment]
Please build kmozillahelper with the "#define DEBUG_KDE" line uncommented and post the output again

**Comment by Brli** [comment]
```
COMMAND: GETSAVEFILENAME
kf5.kio.core: Invalid URL: QUrl("1622084.png")
kf5.kio.core: KSambaShare: Could not find smb.conf!
kf5.kio.core: Invalid URL: QUrl("1622084.png")
OUTPUT: 0
OUTPUT: /tmp/1622084.png
OUTPUT: \1
COMMAND: GETPROXY
OUTPUT: DIRECT
OUTPUT: \1
COMMAND: GETPROXY
OUTPUT: DIRECT
OUTPUT: \1
COMMAND: GETPROXY
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "wss"
OUTPUT: DIRECT
OUTPUT: \1
COMMAND: GETPROXY
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "wss"
OUTPUT: DIRECT
OUTPUT: \1
COMMAND: GETPROXY
OUTPUT: DIRECT
OUTPUT: \1
COMMAND: GETPROXY
OUTPUT: DIRECT
OUTPUT: \1
COMMAND: GETPROXY
(omitted)
```

**Comment by Vogtinator** [comment]
Looks sane to me, kmozillahelper returned the right URL to firefox. Anything beyond this is @wrosenauer territory:

```
OUTPUT: 0
OUTPUT: /tmp/1622084.png
OUTPUT: \1
```

**Comment by Brli** [comment]
lol, thanks for your help.
btw, you're on gtk2 build?

my gtk2 build also suffers from this, I don't know why...

**Comment by Vogtinator** [comment]
I'm currently using a GTK3 build, but I can't remember this being broken at any time...

**Comment by Brli** [comment]
Upload suffers the same problem, they might be fundamentally related...(not sufficient GTK3 patch?)

Close reason: upstream/different repo that mantains kde patchset

**Comment by Vogtinator** [comment]
It could also be related to electrolysis, which is disabled here

**Comment by Brli** [comment]
that maybe it
