### ISSUE TITLE
download works once every two with option "ask every time where download" 

### ISSUE THREAD

**Issue by Houston4444** [openSUSE/kmozillahelper#13]
Maybe since last update of mozilla-kde-support, with the option "ask every time where files are downloaded" (not sure of the exact option name, i use it in french) in firefox settings, download works once every two (approximatively).
When I download a file from any web site, file picker appears and works, but then the file doesn't appears in firefox downloads, and isn't downloaded (as I said it's not systematic, but very very often).

plasma 5.8.6. Neon Distribution 64bits.

**Comment by Vogtinator** [comment]
Can you disable e10s and test again?

**Comment by Houston4444** [comment]
The paramater browser.tabs.remote.autostart was on false, but I don't know why, I have a paramater named browser.tabs.remote.autostart.2 (defined by user , maybe by an extension...), it was on True, I toggled it to False, It seems to work. Thanks

**Comment by Houston4444** [comment]
browser.tabs.remote.autostart.2 exists and is set to True on a new empty profile.

**Comment by anewuser** [comment]
@Vogtinator I'm having this problem even with e10s disabled. I use KDE Neon too. Now at version 5.10, based on Ubuntu 16.04. Aren't openSUSE  users affected?

**Comment by Vogtinator** [comment]
I tried it here, works fine 10/10 times...

Can you enable DEBUG in main.cpp and provide the stdout after it fails?

**Comment by anewuser** [comment]
Launching Firefox from a terminal prints this error when a download fails: 

    kf5.kio.core: Invalid URL: QUrl("pdf-sample.pdf")

>Can you enable DEBUG in main.cpp and provide the stdout after it fails?

How to do that?

**Comment by Vogtinator** [comment]
> Launching Firefox from a terminal prints this error when a download fails:
> 
> ```kf5.kio.core: Invalid URL: QUrl("pdf-sample.pdf")```

That message is expected and harmless.

> How to do that?

You'd need to build kmozillahelper yourself. As that depends on your distro, I won't be able to help much there.

**Comment by Vogtinator** [comment]
Should be fixed by the changes in firefox. If not, please reopen this.

**Comment by ghost** [comment]
Hi, sorry, what changes are you talking about? from what version of firefox we can test again to see if it's already fixed?

**Comment by Vogtinator** [comment]
For openSUSE, you'll need MozillaFirefox-57.0.4 from mozilla:Factory.

For other distros, check that mozilla-kde.patch contains the last two commits from https://www.rosenauer.org/hg/mozilla/log/963651ec972e/mozilla-kde.patch

**Comment by ghost** [comment]
Thanks a lot, i'm currently on neon and tried this with the plasmazila's PPA, gonna ask if the fix will be available there too.
