### ISSUE TITLE
Crashes firefox if run with Qt 5.9

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/kmozillahelper#14]
I have no idea why, but the call to ```deleteLater()``` of the foreign window (firefox) after ```KWindowSystem::setMainWindow``` makes firefox crash due to a ```BadWindow``` X11 error.

Does not happen with Qt 5.8 or earlier.  Probably caused by https://github.com/qt/qtbase/commit/0c6911e5cde24c45d6f2c08b6e71064bdd1eccfa

**Comment by bobwya** [comment]
Just upgraded to Qt 5.9.0 (beta 3) and I'm seeing this issue as well (on Gentoo)...

**Comment by Vogtinator** [comment]
I added a workaround now, can you confirm that the crashes are gone?

**Comment by bobwya** [comment]
Yeah, thanks... That sorts the issue out at this end!
Tested loading torrent files into a qbittorrent webui instance (running on a NAS) using a Plasma 5.9.5 Desktop.

**Comment by Vogtinator** [comment]
This is now being fixed upstream, so I will remove the workaround again.

https://bugreports.qt.io/browse/QTBUG-61140
