### ISSUE TITLE
Firefox crashing entirely with freezing kdialog

### ISSUE THREAD

**Issue by wolftune** [openSUSE/kmozillahelper#18]
opened this kdialog bug: https://bugs.kde.org/show_bug.cgi?id=387521

Should I just close that or maybe knowledgeable folks could comment there?

Someone else posted full output and reproduce instructions at https://github.com/plasmazilla/mozilla-kde-support/issues/30

**Comment by Vogtinator** [comment]
I can reproduce, it's a regression: https://bugzilla.suse.com/show_bug.cgi?id=1074272

**Comment by wolftune** [comment]
@Vogtinator well, in my case, I've had it where everything slows down like crazy, basically freezes, just upon *opening* the dialog (not cancelling). Is that still the same root issue?

**Comment by Vogtinator** [comment]
AFAICT the issue is a dangling reference somewhere in firefox, so basically anything can happen.

It's probably systemd-coredump hogging the CPU in your case.
