### ISSUE TITLE
Scrolling does not match other KDE Apps

### ISSUE THREAD

**Issue by marco-parillo** [openSUSE/kmozillahelper#19]
I use the Firefox KDE integration, packaged on Manjaro KDE as firefox-kde-opensuse, which I believe is re-packaged from the [AUR](https://aur.archlinux.org/packages/firefox-kde-opensuse/).

First, thanks for the KDE integration. Would it be possible to 'fix' the scrolling?

Expected behaviour: When I single click on the FF scrollbar (no matter where), it should go one screen in that direction, like all KDE apps.

Actual behaviour: When I single click on the FF scrollbar, it appears to scroll to the spot where I clicked.

Because this is the only application that I know of that does this, it is a frustrating inconsistency.

[Resolved Upstream Bugzilla from OpenSUSE](https://bugzilla.opensuse.org/show_bug.cgi?id=1104586).

**Comment by Vogtinator** [comment]
That would not be handled by kmozillahelper itself, but by the patches to firefox.

The proper way to implement this is to have this behaviour configurable upstream (if it's not already the case) and then enable it by default in the mozilla/firefox-kde.patch set.

Can you file a bug report upstream?

**Comment by marco-parillo** [comment]
Thank you.

https://bugzilla.mozilla.org/show_bug.cgi?id=1482714

**Comment by marco-parillo** [comment]
Thank you very much. You may close this issue (it is unclear if/how I can myself). It has nothing to do with kmozillahelper.

[Fix](https://bugs.kde.org/show_bug.cgi?id=379773).
[Background](https://bugzilla.opensuse.org/show_bug.cgi?id=1104586).
