### ISSUE TITLE
Button order in print dialog

### ISSUE THREAD

**Issue by dkadioglu** [openSUSE/kmozillahelper#2]
Hi,

would it be possible to fix the button order in the print dialog? At the moment the order is cancel on the left and print on the right which is obviously uncommon in KDE/Plasma. This happens at least with GTK3, I am not sure, if its the case with GTK2. The parameter gtk-alternative-button-order=1 is set in settings.ini as well as in gtkrc.

Thanks in advance.

**Comment by scarabeusiv** [comment]
Actually the print dialog is native to gtk/firefox, the mozhelper does not override anything in there.

**Comment by dkadioglu** [comment]
Thanks for your answer. Obviously this was not the right place for that bugreport. Sorry for the noise.
