### ISSUE TITLE
kmozillahelper not working with Firefox Quatum ESR on latest Mageia 6.1

### ISSUE THREAD

**Issue by Beurt** [openSUSE/kmozillahelper#21]
Hi,
Since Mageia has updated Firefox ESR to Quantum (60.x) kmozillahelper (v. 0.6.5 bundled with the distrib and v. 5.0.2 in testing packages) is not working anymore. For instance, the filepicker is always the annoying GTK3 one, never the Plasma/KDE one. 

Bug has been filed on Mageia bugtracker: https://bugs.mageia.org/show_bug.cgi?id=23638 but the maintainer needs help from upstream.

**Comment by Vogtinator** [comment]
I'm using Firefox 62.0.3 here (openSUSE Tumbleweed) without issues.

kmozillahelper is only a helper binary - the majority of the work is done by a patch to the firefox source.
I guess that just needs to be updated. The latest state can be found at https://www.rosenauer.org/hg/mozilla/file/tip/mozilla-kde.patch

**Comment by Beurt** [comment]
Thanks for your answer. I just reported this back to Mageia team: https://bugs.mageia.org/show_bug.cgi?id=23638
