### ISSUE TITLE
GETDEFAULTFEEDREADER obsolete as of Firefox 64

### ISSUE THREAD

**Issue by wrosenauer** [openSUSE/kmozillahelper#22]
This is just to track that feed reader support has been dropped from Firefox with version 64.0.
Since 60esr still is out it still should be supported but at some point it might be removed.

**Comment by Vogtinator** [comment]
With the desktop portal DBus API support most other parts can be dropped as well and replaced by `setenv("GTK_USE_PORTAL", "1")` or so. Needs some testing though.

I don't see any reason to remove any of the commands in the helper - until KDE Frameworks 6 it will continue to work without any modifications so removing code just makes maintenance harder.

**Comment by wrosenauer** [comment]
Totally fine for me. Just wanted to share the information to get explicit decision.
