### ISSUE TITLE
Filepicker does not show network places

### ISSUE THREAD

**Issue by maverick74** [openSUSE/kmozillahelper#23]
If i go to (e.g.) Google Images and try to upload files from the network i cannot, as it does not show remote folders (only local ones)!

**Comment by Vogtinator** [comment]
This is correct, firefox only supports uploading local files.

**Comment by maverick74** [comment]
Hi @Vogtinator 

isn't there a way to solve this?

LO, for example, uses lo_kde5filepicker and seems to have no problem with network places

**Comment by Vogtinator** [comment]
Here Libreoffice with "kde5" does not support arbitrary URLs either.

**Comment by maverick74** [comment]
hum... weird...

I don't have a problem with it here! I'm on opensuse TW, however. But i can browser remote folders without any problem!

This is a very annoying missing feature!!!

Isn't there any plans to support it?

**Comment by bmwiedemann** [comment]
What are "remote folders" here? SMB (Windows) shares? NFS mounts?
Even a mounted sshfs would count as "local"

**Comment by maverick74** [comment]
SMB in this case

**Comment by maverick74** [comment]
Let me ask another thing: Shouldn't this be "native" of kde or something?

I mean, why is there a need for a kmozillahelper? Shouldn't it just call a plasma specific process that would deal with this (KIO, i think) and that would be common for all programs and show up the same to all of them?

what am i missing here?!

**Comment by bmwiedemann** [comment]
So that would be a `\\host\path\file` type path then?
https://en.opensuse.org/Samba#How_to_use_the_client has an example for proper mounting of a SMB share, so it would become a "local" filesystem to all applications.

**Comment by bmwiedemann** [comment]
And firefox is not a KDE program - I think it used GTK, so it would not know about KDE-specifics itself.

**Comment by Vogtinator** [comment]
> I'm on opensuse TW

Me too.

> I mean, why is there a need for a kmozillahelper? Shouldn't it just call a plasma specific process that would deal with this (KIO, i think) and that would be common for all programs and show up the same to all of them?

Firefox does not have any interface with Plasma/KIO other than kmozillahelper. To make this work, it would be necessary to replace large parts of firefox' IO internals with KIO specifics.

**Comment by maverick74** [comment]
@Vogtinator @bmwiedemann  ok, but i have the same problem with Falkon, Krita, Calligra, etc and they're all KDE (and Firefox is using the kde open dialog as well) so... why don't they work either? :)

(sorry for all my questions - but is a frustrating "thing" )

**Comment by Vogtinator** [comment]
> @Vogtinator @bmwiedemann ok, but i have the same problem with Falkon, Krita, Calligra, etc and they're all KDE (and Firefox is using the kde open dialog as well) so... why don't they work either? :)

Falkon uses Qt WebEngine (which is just repackaged chromium) without KIO integration. Krita and Calligra should work fine.

**Comment by maverick74** [comment]
@Vogtinator so... that means that i probably have some problem on my machine :)
(Or that there is a bug somewhere)

**Comment by Vogtinator** [comment]
@maverick74 Probably. While it probably makes sense to have this discussion elsewhere, I'm not sure where. What happens with the following?

- Kate's file dialog
- "kdialog --getopenurl"
- "kdialog --getopenfilename"

**Comment by maverick74** [comment]
I understand. I'm sorry but I didn't get any help anywhere else.

I'm out of office ATM in about an hour I'll reply you with an answer to your questions above.

You mentioned above this is the result lack of support of arbitrary URLs (from what understand). Isn't this planed to be supported in kmozillahelper?

**Comment by Vogtinator** [comment]
> You mentioned above this is the result lack of support of arbitrary URLs (from what understand). Isn't this planed to be supported in kmozillahelper?

This isn't something that can be implemented in kmozillahelper, it's a new feature for firefox.

**Comment by maverick74** [comment]
Ok. If that is what's needed to be able to browse remote folders, Then it's something to submit as a bug in Mozilla. :)

Thanks for clarifying that part.

I'll get back here asap with those answers

**Comment by maverick74** [comment]
@Vogtinator 

> - Kate's file dialog

Shows remote locations

> - "kdialog --getopenurl"

Shows remote locations

> - "kdialog --getopenfilename"

**Does not show** remote locations

**Comment by maverick74** [comment]
@Vogtinator
Is there any real diference, in terms of function, between

kdialog --getopenurl and 
kdialog --getopenfilename 

that justifies having the last instead of the fist for file uploads?

**Comment by Vogtinator** [comment]
Yes. The former returns an URL (file:///foo/bar, smb://host/path/file, desktop:/file) while the latter a local file path. Firefox does not support URLs for file operations.
