### ISSUE TITLE
Thunderbird save dialog incorrectly has "Mozilla Firefox" in window title

### ISSUE THREAD

**Issue by logological** [openSUSE/kmozillahelper#26]
As shown in the screenshot below, the Save dialog that appears by triggering various commands in Thunderbird (e.g., File->Save As->File from the pull-down menu, or right-clicking on an attachment and selecting "Save As" from the context menu) includes the text "Mozilla Firefox" in the window title. Surely this text shouldn't be there at all, or else it should be "Thunderbird" instead.

![Screenshot of Thunderbird Save dialog showing bug](https://user-images.githubusercontent.com/831326/62274290-dde19a80-b43f-11e9-9e68-553f913508dc.png)

The problem occurs only when using the openSUSE distribution of Thunderbird together with the kmozillahelper package.  The problem does not occur when using [the official Thunderbird tarball](https://download.mozilla.org/?product=thunderbird-60.8.0-SSL&os=linux64&lang=en-US) (whether or not kmozillahelper is installed), and the problem does not occur with the openSUSE distribution of Thunderbird when kmozillahelper is not installed.  So I'm guessing that the problem is with kmozillahelper.

I am running MozillaThunderbird-60.8.0-1.5.x86_64 and kmozillahelper-5.0.4-10.2.x86_64 on openSUSE Tumbleweed 20190717.

I also reported this problem on Thunderbird's Bugzilla ([Bug 1569947](https://bugzilla.mozilla.org/show_bug.cgi?id=1569947)) but the consensus there is that this is not Thunderbird's problem.

**Comment by wrosenauer** [comment]
It could actually be a mistake in the patches we apply to Thunderbird. Typically the patchset is identical between Firefox and Thunderbird so it might be just a copy issue. I will check the coming days unless someone here can confirm it's in kmozillahelper inbetween.

**Comment by Vogtinator** [comment]
It's likely taking it from here: https://github.com/openSUSE/kmozillahelper/blob/master/main.cpp#L68

@logological: Can you test a patch?

**Comment by logological** [comment]
Probably, yeah.

**Comment by Vogtinator** [comment]
Please give https://github.com/openSUSE/kmozillahelper/pull/27 a try.

**Comment by logological** [comment]
@Vogtinator: The patch works for me.  Looks good to merge into master.
