### ISSUE TITLE
kmozillahelper flooding journal with entries.

### ISSUE THREAD

**Issue by biggestsonicfan** [openSUSE/kmozillahelper#29]
As seen in this issue [here](https://github.com/furyutei/twMediaDownloader/issues/56), kmozilla helper is flooding my journal with a single entry:

`kf.kio.widgets.kdirmodel: No node found for item that was just removed: QUrl("file://[location removed].zip")`

It would be very helpful in understanding how to resolve this error or where kmozillahelper even is reading this value so I can expunge it from my error logs.

kmozillahelper also appears to be freezing my Firefox when trying to save images, particularly when I "mouse button up" on the "Save Image As" option, but I do not know how to properly diagnose that issue.

Also, is this a dead project?

**Comment by Vogtinator** [comment]
> It would be very helpful in understanding how to resolve this error or where kmozillahelper even is reading this value so I can expunge it from my error logs.

kmozilahelper itself doesn't actually emit this, it's from KIO, most likely through the open/save file dialog. Nothing special happens here, so this is most likely an issue with every application using the KIO file picker.

If you can reproduce this with other applications (like `kdialog --getopenfilename`) running in parallel, this should be reported at https://bugs.kde.org instead.

> Also, is this a dead project?

No, there just aren't many bugs!

**Comment by biggestsonicfan** [comment]
> kmozilahelper itself doesn't actually emit this, it's from KIO, most likely through the open/save file dialog. Nothing special happens here, so this is most likely an issue with every application using the KIO file picker.

Ah, so my rabbit hole goes deeper. Seems like that is the right track. I believe what specifically is happening with this particular error is the file was generated, but not saved, then generated and saved again? I can't get the error to reproduce with a different result. However, I had reformatted my system and reloaded a fresh OpenSUSE install and now got it again. If it's a kde bug all along, whew. I'll just be glad once it's fixed. I'll report back here if the folks at kde can help me narrow this down and either expand or close the issue once I have something more conclusive.

>No, there just aren't many bugs!

Fair enough!

**Comment by Vogtinator** [comment]
> > kmozilahelper itself doesn't actually emit this, it's from KIO, most likely through the open/save file dialog. Nothing special happens here, so this is most likely an issue with every application using the KIO file picker.
> 
> Ah, so my rabbit hole goes deeper. Seems like that is the right track. I believe what specifically is happening with this particular error is the file was generated, but not saved, then generated and saved again?

Yes, something like that is what I expect as well. If a process is really quick with file creation and deletion, it might run into this.

> I can't get the error to reproduce with a different result. However, I had reformatted my system and reloaded a fresh OpenSUSE install and now got it again. If it's a kde bug all along, whew. I'll just be glad once it's fixed. I'll report back here if the folks at kde can help me narrow this down and either expand or close the issue once I have something more conclusive.

Did you report it upstream?

**Comment by biggestsonicfan** [comment]
I've tried bringing this up to the KDE community but I've only been met with silence every time. I've also discovered why it's flooding my entries: Each time a save dialog box is created via kmozillahelper, another warning is added to added to the journal. As I save several thousand files via Firefox a day, this explains the flood of entries.

**Comment by Vogtinator** [comment]
Unfortunately there's nothing that can be done about this from the `kmozillahelper` side, this can only be fixed in KIO.

**Comment by biggestsonicfan** [comment]
Could you at least explain why kmozillahelper creates and removes these entries in the first place? Why are they necessary? Can kmozillahelper be forked to prevent creating these entries? Can you not create nodes for these items kmozillahelper is creating?

<s>EDIT: The best "solution" was to launch kdebugdialog5 and untick "KIO" logging. This solves nothing, but does alleviate the excess number of log entries.</s> This actually does nothing. The logging still occurs.

EDIT2: A filing with KDE has been made: https://bugs.kde.org/show_bug.cgi?id=439961

**Comment by Vogtinator** [comment]
> Could you at least explain why kmozillahelper creates and removes these entries in the first place?

It does not. kmozillahelper opens Qt file dialogs, which end up in KIO code, which create those messages.

**Comment by biggestsonicfan** [comment]
Then why do my other applications which use Qt file dialogs not create these same warning messages? I am also not talking specifically about the warning itself, that yes, actually produces the warning message logged, I am talking about the KFileItemList being passed to void _k_slotDeleteItems not having what is expected of it: 
https://github.com/KDE/kio/blob/c88c4c65567ed089902848b58aa62cd6563dd933/src/widgets/kdirmodel.cpp#L577

In both cases the warning is displayed, the code is only reached if there is no node. Where in the pipeline relative to kmozillahelper should "items" get passed through to KIO?

**Comment by biggestsonicfan** [comment]
While it doesn't address the root cause, adding `export QT_LOGGING_RULES="kf.kio.widgets.kdirmodel.warning=false"` to my `~/.profile` seems to suppress logging these warnings!
