### ISSUE TITLE
Please tag a new version

### ISSUE THREAD

**Issue by Thaodan** [openSUSE/kmozillahelper#3]
I want to package kmozillahelper but the last tag is the old version.

**Comment by scarabeusiv** [comment]
Well even tho we can tag new version without the fixed FIXME bugs that are in the code it is quite complex.

Esp that overwrite without asking bug needs to be sorted out, because otherwise people would be quite angry for rewritting their own stuff.

**Comment by Thaodan** [comment]
so whats the way its going on? Should I always pull the latest git?

**Comment by scarabeusiv** [comment]
Or sent PR to fix the issues. It does not make much sense to package this to users anyway it is quite broken and they would be suppised how it breaks for them.

I am not developing this thing nor have time to do it. I fixed the easy bugs and pulled the commit from the archlinux guys but thats about it. Lubos Lunak whom wrote this is not interested in it either so simply put just get someone to be willing to maintain it, openSUSE will gladly give him access and we can tag a version you desire.

**Comment by Vogtinator** [comment]
New versions are prepared and tagged. 5.0.0 is due soon.
