### ISSUE TITLE
[KDE Plasma / Firefox 98.0+] kmozillahelper causes firefox to automatically open files after download

### ISSUE THREAD

**Issue by DarkWav** [openSUSE/kmozillahelper#35]
[openSUSE Bugzilla report](https://bugzilla.suse.com/show_bug.cgi?id=1197319)

openSUSE Tumbleweed's firefox build opens most files after downloading since version 98.0 without any inquiries when kmozillahelper is installed when in a KDE session. Without it, it works like intended.

Steps to reproduce:
1. Install latest openSUSE Tumbleweed KDE x86_64 (or load up live iso)
2. Install the MozillaFirefox and kmozillahelper packages from openSUSE Tumbleweed repos
3. Launch Firefox.
4. Go to https://www.mozilla.org/en-US/firefox/download/thanks/

Expected behavior:
Firefox downloads firefox and does nothing thereafter.

Observed behavior:
Firefox downloads firefox and automatically opens the bz2 archive in Ark/some other Archive manager without a single inquiry.

Notes:
- This result does not happen with Mozilla's official firefox builds, with the same configuration. They seem to not be able to integrate with kmozillahelper though.
- If WINE is installed on the system this can get quite dangerous as some .exe file you download could automatically get executed with wine without any inquiries whatsoever in some cases.

**Comment by Vogtinator** [comment]
I can reproduce the issue. I don't think this is on the kmozillahelper side, it doesn't receive any command to open downloaded files. So let's continue that on bugzilla.
