### ISSUE TITLE
kmozillahelper swaps paths with multiple dialogs open

### ISSUE THREAD

**Issue by biggestsonicfan** [openSUSE/kmozillahelper#36]
Greetings once again,

I have confirmed and reproduced an issue specifically tracking it down to kmozillahelper after a recent update to Firefox 100.

If I initiate a download (file A) and save another file (file B), if B's dialog box appears first, then A's dialog box appears second, saving the only accessible dialog box B will save the path/name using dialog box A's information, and the data of file A will be saved wherever file B was to be saved:

Steps to reproduce:

1. Visit https://easyupload.io/6beruf
2. Left click "Download" to initiate a delayed file save dialog box of a Firefox logo (512px-Mozilla_Firefox_logo_2013.svg.png)
3. Quickly right click and "Save image as" the "Easyupload.io" logo (logo-new.webp)
4. The dialog box for the Easyupload.io logo should appear first, then allow the Firefox logo dialog box to appear second. Both dialog boxes must be open at the same time.
5. Save the "512px-Mozilla_Firefox_logo_2013.svg.png" dialog box with the "Save" button to allow the first dialog box to be interacted with.
6. Save the "logo-new.web" file with that dialog box.
7. The contents of "512px-Mozilla_Firefox_logo_2013.svg.png" and "logo-new.web" should be swapped.

I have confirmed this issue is not reproducible without kmozillahelper installed. I have had to use places.sqlite and sql command forensic work to track down many files that have been saved incorrectly.

I am on OpenSUSE Tumbleweed with KDE 5.93.0 / Plasma 5.24.5 on kernel 5.17.4-1 and Firefox 100.

**Comment by Vogtinator** [comment]
Yes, this is a known issue with the protocol design. You basically have to close the dialogs in the inverse order that they appear, otherwise they desync.

To mitigate that I added a limit that only a dialog can be open at once, but that wasn't well received and got reverted in favor of keeping this bug... The protocol won't be redesigned as the future is with XDG portals. So this is a WONTFIX, unfortunately.

**Comment by biggestsonicfan** [comment]
Yikes, I've been using kmozillahelper with multiple dialogs on and off during my struggles with the other issues but it's only recently happened, but this is the _first_ encounter I've ever had with this particular one.

**Comment by biggestsonicfan** [comment]
Been nearly a year and I'm still running into residual issues from this mess.

**Comment by Vogtinator** [comment]
Can you use XDG portals instead?
