### ISSUE TITLE
Thumbnails no longer shown in file dialog box

### ISSUE THREAD

**Issue by biggestsonicfan** [openSUSE/kmozillahelper#37]
Not entirely sure what went wrong but I no longer have thumbnails in my dialog boxes. I feel that this is the strong, and main pull, point of using kmozillahelper over the default kde dialog box, and it seems to have stopped working.

**Comment by Vogtinator** [comment]
Does it still use the right file picker but without thumbnails? Does `kdialog --getopenfilename` still show thumbnails?

**Comment by biggestsonicfan** [comment]
Apparently `kdialog --getopenfilename` does also not show thumbnails.

**Comment by Vogtinator** [comment]
Ok, so not an issue with `kmozillahelper`. If it only affects some locations it might be a corrupt cache or the limit for remote locations is set too low. If it affects all locations something might be broken, maybe `kio-extras5` missing or the `thumbnail:` protocol broken some other way.

**Comment by biggestsonicfan** [comment]
Absolutely unreal how many issues arise with using kmozillahelper that can't be kmozillahelper's fault.

**Comment by Vogtinator** [comment]
kmozillahelper is tiny and just glues stuff together.

**Comment by biggestsonicfan** [comment]
I had about 4 other issues I've been putting off reporting but I guess I should just take those over to KDE (who does nothing with them)

**Comment by biggestsonicfan** [comment]
... the goddamn "Show Preview" button somehow got unset... I am so embarrassed... :sob:
