### ISSUE TITLE
For KDE 5

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/kmozillahelper#4]
How could this helper support KDE 5? In openSUSE 42.1, Firefox still use the KDE 4 file browser, rather than KDE 5 file browser.

**Comment by scarabeusiv** [comment]
It is not fixed and it has issues.
The package is no longer developed but I will accept pullrequest and fixes.
The biggest issue of this git version is that the filtering of filves does not work and sometimes it gets stuck.
