### ISSUE TITLE
Browser window is not activated when opening links

### ISSUE THREAD

**Issue by pallaswept** [openSUSE/kmozillahelper#43]
When clicking links in some external apps (eg openoffice), while using a Wayland session, the link is opened in firefox, but the browser window is not focussed or activated.

Please see here for some history: https://bugzilla.suse.com/show_bug.cgi?id=1215852

Thanks for any help you can offer :)

**Comment by Vogtinator** [comment]
No idea how that can happen, kmozillahelper isn't involved in FF window management or opening URLs.

**Comment by fkru** [comment]
> No idea how that can happen, kmozillahelper isn't involved in FF window management or opening URLs.
I am also puzzled. The issue described at https://bugzilla.suse.com/show_bug.cgi?id=1215852 is related to Wayland only, within X11 everything works fine, even if kmozillahelper installed.

**Comment by pallaswept** [comment]
I just tested removing kmozillahelper, and the issue persisted - After a reboot, I opened FF, opened Writer, typed in a URL, opened it, and the firefox icon flashed at me while the window remained in the background.
I'm sorry, I can't replicate your workaround @fkru . I think this case might have been raised in error, sorry about that.

**Comment by fkru** [comment]
> I just tested removing kmozillahelper, and the issue persisted - After a reboot, I opened FF, opened Writer, typed in a URL, opened it, and the firefox icon flashed at me while the window remained in the background. I'm sorry, I can't replicate your workaround @fkru . I think this case might have been raised in error, sorry about that.

I completely agree, that's exactly what I meant in https://bugzilla.suse.com/show_bug.cgi?id=1215852#c29.

**Comment by fkru** [comment]
So, would you like to close this ticket here?

**Comment by pallaswept** [comment]
Apologies @Vogtinator

**Comment by nerdoc** [comment]
Hmmm. This bug here links to https://bugzilla.suse.com/show_bug.cgi?id=1215852#c29, which again links back to here with its last comment at time of writing.

**Comment by pallaswept** [comment]
This bug was opened in error. I thought I was being asked to open it, so I did, but I had misunderstood. Pretend this one doesn't exist :)
