### ISSUE TITLE
Save file dialog does not prefill filename when title have "xxx : xxx"

### ISSUE THREAD

**Issue by nx-99** [openSUSE/kmozillahelper#7]
For exsemple this page https://github.com/openSUSE/kmozillahelper

**Comment by Vogtinator** [comment]
Can you retest this with the current version and provide an example with screenshots?
Thanks!

**Comment by Vogtinator** [comment]
Nevermind, I was able to reproduce it. It is sadly a bug in KIO so I can't fix it here (maybe add a workaround though) and I reported it here: https://bugs.kde.org/show_bug.cgi?id=376365

**Comment by Vogtinator** [comment]
I found a workaround, but unfortunately the workaround would break it entirely once the bug is fixed, so I won't apply it. In case you want to do it yourself:

```
diff --git a/main.cpp b/main.cpp
index 6256b51..7da1384 100644
--- a/main.cpp
+++ b/main.cpp
@@ -352,7 +352,11 @@ bool Helper::handleGetOpenOrSaveX(bool url, bool save)
 
     QFileDialog dialog(nullptr, title, defaultPath.path());
 
-    dialog.selectFile(defaultPath.fileName());
+    // Workaround for kde#376365
+    if(defaultPath.fileName().indexOf(":") != -1)
+        dialog.selectFile(QUrl::toPercentEncoding(defaultPath.fileName()));
+    else
+        dialog.selectFile(defaultPath.fileName());
     dialog.setNameFilters(filtersParsed);
     dialog.setOption(QFileDialog::DontConfirmOverwrite, false);
     dialog.setAcceptMode(save ? QFileDialog::AcceptSave : QFileDialog::AcceptOpen);

```

**Comment by nx-99** [comment]
This Workaround work, but when change directory to save, file name disappears.
Second, save only complete pag. not only HTML .
Thank.

**Comment by Vogtinator** [comment]
I'm sorry, I don't understand what you mean.

**Comment by Vogtinator** [comment]
I made a fix for plasma-integration: https://phabricator.kde.org/D4579 and added it to the openSUSE package.

**Comment by Vogtinator** [comment]
Fix is now pushed upstream and will likely be part of Plasma 5.10, 5.9.2 and 5.8.6.
