### ISSUE TITLE
[cancel open dialog] - segfault when multi process (Electrolysis) is active

### ISSUE THREAD

**Issue by scachemaille** [openSUSE/kmozillahelper#8]
Hello.
I don't know if it's a bug in kmozillahelper but when the multi process windows (Electrolysis) on firefox is active,  if a page ask for an open file dialog (upload image as example) and we click on cancel of the dialog to abort. firefox crash with a segfault.

```
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "wss"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "wss"
[Child 8205] ###!!! ABORT: Aborting on channel error.: file /build/firefox-kde/src/firefox-51.0.1/ipc/glue/MessageChannel.cpp, line 2056
[Child 8205] ###!!! ABORT: Aborting on channel error.: file /build/firefox-kde/src/firefox-51.0.1/ipc/glue/MessageChannel.cpp, line 2056
Segmentation fault (core dumped)

```
tested with kmozillahelper 0.6.5 from manjaro repository and kmozillahelper 4.9.15-1 from AUR, they both crash. and with firefox-kde 51.0.1-1 from manjaro
https://forum.manjaro.org/t/firefox-kde-segfault/16894

**Comment by Vogtinator** [comment]
This is a bug in the firefox part, which I have no idea about.
Please add your findings on the bug in the openSUSE bug tracker: https://bugzilla.opensuse.org/show_bug.cgi?id=1015998

I'll close this one here.
