### ISSUE TITLE
Save Dialog does not come up at all. 

### ISSUE THREAD

**Issue by llelectronics** [openSUSE/kmozillahelper#9]
After the kf5 base switch some save dialogs don't open up the Save Dialog. 
(Always ask where to save is on)
If you try downloading for example this here: https://uappexplorer.com/app/ktuberling.kde
Click on Download amd64 it shows a firefox native Save File/ Cancel Dialog. (the small one without the option boxes)
If I click on Save File it should open up the kde/plasma native file dialog but does nothing basically. 
From this point on the file dialogs don't show up anywhere no matter what action you perform (open/save page ...)

**Comment by shadeslayer** [comment]
This happens to any bin ( or app/octet-stream ) files btw

**Comment by shadeslayer** [comment]
And looks like the helper crashes after one downloads the binary file

```
#0  0x00007f06024e65dd in ppoll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f0602a7ea21 in qt_safe_poll(pollfd*, unsigned long, timespec const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f0603f26917 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#3  0x00007f0603f24105 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#4  0x00007f0603f1a89f in QAbstractSocket::waitForReadyRead(int) () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#5  0x00007f05fa8cce6d in ?? () from /usr/lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#6  0x00007f05fa90f5d0 in KIO::SlaveBase::dispatchLoop() () from /usr/lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#7  0x00007f05f235fffa in kdemain () from /usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/file.so
#8  0x00000000004084bb in ?? ()
#9  0x00000000004096a4 in ?? ()
#10 0x000000000040a0d1 in ?? ()
#11 0x0000000000404d9d in ?? ()
#12 0x00007f06024272b1 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x0000000000405ada in _start ()
```

**Comment by Vogtinator** [comment]
Should be fixed now, please reopen if it appears again!

**Comment by shadeslayer** [comment]
@Vogtinator this does not however fix the issue of the save file dialog being broken for application/octet-stream file types

**Comment by Vogtinator** [comment]
Do you have an example that still fails?

**Comment by shadeslayer** [comment]
Ah, I see the old dialog and then clicking "Save File" brings up the KDE dialog. So it looks fixed :)
